import { ChatBot, Footer, PcHeader } from '@/components'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Head from 'next/head'
import '../styles/globals.css'

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="naver-site-verification" content="228274ae7b7be03ce5edf28d63d13d8e979750f5" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <PcHeader />
        <div>
          {children}
          <ChatBot />
        </div>
        <Footer />
      </body>
    </html>
  )
}
